# Default values for cray-oauth2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.1.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# The Keycloak client secret includes the client ID, client secret, and
# discovery URL. It is configured as part of keycloak_deploy role.
oauth2ClientSecret: keycloak-gatekeeper-client

# The URL to which traffic is forwarded after authentication (and
# authorization). This is expected to be the Istio ingress gateway.
upstreamUrl: "https://istio-ingressgateway.istio-system.svc.cluster.local/"

# The hostnames that keycloak-gatekeeper will proxy. Hosts must be 
# overridden with valid values, a single value here is used to ensure
# the chart builds successfully (e.g., the certificate chart requires
# at least one host to use as commonName + first SAN)
hosts:
- replace_me

# Additional /etc/hosts configuration for keycloak-gatekeeper pod(s).
# Necessary on systems where the discovery URL in keycloakClientSecret is not
# resolvable from the keycloak-gatekeeper pod (e.g., groot-ncn-w001).
hostAliases: []

# Certificate secretName
certificateSecretName: "oauth2-proxy-certs"
