# Default values for cray-oauth2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.1.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
priorityClassName: csm-high-priority-service

# The OAuth2-Proxy Secret includes the cookie-secret. This is created
# by a Sealed Secret.
oauth2ProxySecret: cray-oauth2-proxy

# The Keycloak client secret includes the client ID, client secret, and
# discovery URL. It is created by the keycloak-setup tool.
oauth2ClientSecret: oauth2-proxy-client

# The URL to which traffic is forwarded after authentication (and
# authorization). This is expected to be the Istio ingress gateway.
upstreamUrl: "https://istio-ingressgateway.istio-system.svc.cluster.local/"

# The address pool that will be used.
metalLbAddressPool: customer-management

# The hostnames that oauth2-proxy will proxy. Hosts must be 
# overridden with valid values, a single value here is used to ensure
# the chart builds successfully (e.g., the certificate chart requires
# at least one host to use as commonName + first SAN)
hosts:
- replace_me

# Additional /etc/hosts configuration for oauth2-proxy pod(s).
# Necessary on systems where the discovery URL in keycloakClientSecret is not
# resolvable from the oauth2-proxy pod (e.g., groot-ncn-w001).
hostAliases: []

# Certificate secretName
certificateSecretName: "oauth2-proxy-certs"

# The standard arguments for each oauth2-proxy pod
arguments:
- --proxy-prefix=/oauth
- --provider=oidc
- --https-address=:8443
- --skip-provider-button=true
- --pass-access-token=true
- --insecure-oidc-allow-unverified-email=true
# Workaround to get accounts without emails able to authenticate
- --oidc-email-claim=sub
- --email-domain=*
- --tls-cert-file=/etc/tls/tls.crt
- --tls-key-file=/etc/tls/tls.key
- --provider-ca-file=/etc/tls/ca.crt

# A list of sealedSecrets passed in to be deployed.
sealedSecrets: []
